In [ ]:
import pandas as pd
from sqlalchemy import create_engine

df = {
    'customers': pd.read_csv('../../cleaned_data/customers.csv'),
    'orders': pd.read_csv('../../cleaned_data/orders.csv'),
    'order_items': pd.read_csv('../../cleaned_data/order_items.csv'),
    'payments': pd.read_csv('../../cleaned_data/payments.csv'),
    'reviews': pd.read_csv('../../cleaned_data/reviews.csv'),
    'products': pd.read_csv('../../cleaned_data/products.csv'),
    'sellers': pd.read_csv('../../cleaned_data/sellers.csv'),
    'geolocation': pd.read_csv('../../cleaned_data/geolocation.csv'),
}

engine = create_engine('postgresql://postgres:pass@localhost:5432/postgres')

for name, table in df.items():
    table.to_sql(name, engine, if_exists='replace', index=False)
    print(f"loaded {name} into postgres")

loaded customers into postgres
loaded orders into postgres
loaded order_items into postgres
loaded payments into postgres
loaded reviews into postgres
loaded products into postgres
loaded sellers into postgres
loaded geolocation into postgres

In [ ]:
# top 10 product categories by total revenue
# INNER JOIN because we only want products that were actually part of a real order item
query1 = """
SELECT p.product_category_name, SUM(o.price) AS total_revenue
FROM order_items o
INNER JOIN products p ON o.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY total_revenue DESC
LIMIT 10;
"""
pd.read_sql(query1, engine)

    product_category_name  total_revenue
0            beleza_saude     1258681.34
1      relogios_presentes     1205005.68
2         cama_mesa_banho     1036988.68
3           esporte_lazer      988048.97
4  informatica_acessorios      911954.32
5        moveis_decoracao      729762.49
6              cool_stuff      635290.85
7   utilidades_domesticas      632248.66
8              automotivo      592720.11
9      ferramentas_jardim      485256.46

In [ ]:
# repeat customer rate: customers with more than 1 order
# using inner join because we only want customers that have actually placed more than 1order
query2 = """
SELECT COUNT(*) AS repeat_customers
FROM (
    SELECT c.customer_unique_id, COUNT(o.order_id) AS order_count
    FROM orders o
    INNER JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
    HAVING COUNT(o.order_id) > 1
) AS repeat_customers_table;
"""
pd.read_sql(query2, engine)

   repeat_customers
0              2997

In [ ]:
# average delivery time by state
#using left join because we want to include all customers, even those who haven't received their orders yet 
query3 = """
SELECT c.customer_state,
       AVG(EXTRACT(EPOCH FROM (o.order_delivered_customer_date::timestamp - o.order_purchase_timestamp::timestamp)) / 86400) AS avg_delivery_days
FROM orders o
LEFT JOIN customers c ON o.customer_id = c.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_state
ORDER BY avg_delivery_days;
"""
pd.read_sql(query3, engine)

   customer_state  avg_delivery_days
0              SP           8.761357
1              PR          11.991582
2              MG          12.010258
3              DF          12.967568
4              SC          14.959297
5              RS          15.300276
6              RJ          15.310053
7              GO          15.606339
8              MS          15.618319
9              ES          15.789307
10             TO          17.658063
11             MT          18.055756
12             PE          18.448323
13             RN          19.278156
14             BA          19.335466
15             RO          19.372037
16             PI          19.457098
17             PB          20.426768
18             AC          21.035713
19             CE          21.266579
20             SE          21.519788
21             MA          21.572976
22             PA          23.772917
23             AL          24.543855
24             AM          26.425991
25             AP          27.185068
26             RR          29.387546